GRANT ALL PRIVILEGES ON DATABASE b3_chatbot TO b3chat;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO b3chat;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO b3chat;
ALTER TABLE public.chat_history OWNER TO b3chat;
ALTER TABLE public.feedback_log OWNER TO b3chat;
ALTER TABLE public.knowledge_cache OWNER TO b3chat;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO b3chat;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO b3chat;
